USE [master]
GO

CREATE DATABASE [SharesTest]
    CONTAINMENT = NONE
    ON  PRIMARY
    ( NAME = N'SharesTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.LOCAL\MSSQL\DATA\SharesTest.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
    LOG ON
    ( NAME = N'SharesTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.LOCAL\MSSQL\DATA\SharesTest_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
    WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    begin
        EXEC [SharesTest].[dbo].[sp_fulltext_database] @action = 'enable'
    end
GO

ALTER DATABASE [SharesTest] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [SharesTest] SET ANSI_NULLS OFF
GO

ALTER DATABASE [SharesTest] SET ANSI_PADDING OFF
GO

ALTER DATABASE [SharesTest] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [SharesTest] SET ARITHABORT OFF
GO

ALTER DATABASE [SharesTest] SET AUTO_CLOSE ON
GO

ALTER DATABASE [SharesTest] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [SharesTest] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [SharesTest] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [SharesTest] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [SharesTest] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [SharesTest] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [SharesTest] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [SharesTest] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [SharesTest] SET  DISABLE_BROKER
GO

ALTER DATABASE [SharesTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [SharesTest] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [SharesTest] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [SharesTest] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [SharesTest] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [SharesTest] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [SharesTest] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [SharesTest] SET RECOVERY SIMPLE
GO

ALTER DATABASE [SharesTest] SET  MULTI_USER
GO

ALTER DATABASE [SharesTest] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [SharesTest] SET DB_CHAINING OFF
GO

ALTER DATABASE [SharesTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [SharesTest] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [SharesTest] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [SharesTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SharesTest] SET  READ_WRITE
GO


